name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - hw14
  pull_request:
    branches:
      - master
      - hw14
    paths:
      - .github/workflows/registration.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Calculate test coverage
        run: mvn jacoco:report

      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco

     # - name: Run static code analysis
    #  run: mvn checkstyle:check

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/lesam19092/fintech:latest .  # Tag for GitHub Container Registry

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/lesam19092/fintech:latest

